### ISSUE TITLE
Update documentation regarding dmlab2d

### ISSUE THREAD

**Issue by ashok-arora** [deepmind/meltingpot#139]
> If there is no appropriate wheel (e.g. M1 chipset) you will need to install [dmlab2d](https://github.com/deepmind/lab2d) and build the wheel yourself (see [install-dmlab2d.sh](https://github.com/deepmind/meltingpot/blob/main/install-dmlab2d.sh) for an example installation script that can be adapted to your setup).

Hey, the new release of dmlab2d has wheels for M1 chipset too, can I update the documentation and remove the `install-dmlab2d.sh` script? 

On a similar note, would it be possible to build wheels for `meltingpot`?

**Comment by duenez** [comment]
Hello, we are in the process of cleaning this up on our end. Thanks for your patience.

**Comment by jagapiou** [comment]
Thanks for the heads up. I've updated the README.md. Not sure we can yet get rid of the `./install-dmlab2d.sh` since you currently need to know which wheel to install (you can't point `pip --find-links` or `pip --index-url` at a GitHub release).

We're looking into getting the dmlab2d wheels added to PyPi and then we'd be able to do likewise with MeltingPot.

**Comment by theo-michel** [comment]
The install-dmlab2d.sh is still necessary for some versions of ubuntu I think.

**Comment by jagapiou** [comment]
Since `meltingpot` (and `dmlab2d`) is now `pip` installable I have removed the info on installing `dmlab2d` and moved `install-dmlab2d.sh` to be a `install.sh` script in `dmlab2d` itself.

If there are any problems with `dmlab2d` please raise them at https://github.com/deepmind/lab2d/issues
