### ISSUE TITLE
Field of view visualisation

### ISSUE THREAD

**Issue by olipinski** [deepmind/meltingpot#167]
Hi!

I am working to replicate the results from the Hidden Agenda paper, and was wondering if there was the best way to add field of view visualisation to the renders? I think this would be very useful for evaluation, to see what the agents can focus on.

Currently, my best guess is to modify the WORLD.RGB observation to add borders or a tint to the agents' FOV. Is there a better way?

Thanks!

**Comment by duenez** [comment]
Hello,

I'm not sure I completely understand what you mean. Do you mean that you want to see what agents can see, but only on the `"WORLD.RGB"` observation, and not for learning? If that's the case, you could achieve this with direct post processing. Since you can extract position and orientation of all agents (using debug observations, disabled by default), you can then take the WORLD.RGB and add borders or tint, like you suggest.

At some point we were thinking about implementing a view system that would respect walls (i.e. not being able to see beyond a wall bend), but I don't think that's what you are talking about, right?

**Comment by olipinski** [comment]
Yes, I would like to be able to highlight what the agents can see on the `WORLD.RBG` observation, similar to the figure below.

![example](https://github.com/deepmind/meltingpot/assets/5785856/cee86441-4b3b-45d0-a919-f403ce2d2f8d)

Thank you for the pointers with the debug observations! I was hoping there would be an easier way to do this, to not slow down the simulation by having more observations being added.

And yes, the walls are not an issue for me.

Thanks you!
