### ISSUE TITLE
Visualize environment for substrate as well as scenario

### ISSUE THREAD

**Issue by kinalmehta** [deepmind/meltingpot#33]
For substrate using WORLD.RGB from any one of the agents seems to do the job.
**BUT**
I can't seem to find a way to visualize the environment for a scenario except by adding WORLD.RBG to the permitted keys. Is there any other possible way to do that?

**Comment by duenez** [comment]
In general, we want to be strict about scenarios. Since those are the actual tests, we do to not have any extra information there that you are not supposed to use at test-time. That's why we tend to hide everything there. If you want to debug or visualise what's going on, feel free to edit the permitted keys. Does that make sense?

**Comment by kinalmehta** [comment]
Thanks @duenez. 
I was doing exactly as you suggested first. But the second approach worked perfectly and looks like a more neat way to approach it without making any changes to the internal library.
Thanks a lot :D
