### ISSUE TITLE
Suppress warning

### ISSUE THREAD

**Issue by GoingMyWay** [deepmind/meltingpot#36]
Hey, dear authors, I saw many warnings, shown below. It would be great if we can suppress these warnings.

```
W @/home/aiops/user/Projects/Github/DeepMind/meltingpot/meltingpot/lua/modules/base_simulation.lua:225] GameObject 'scene' did not have a Transform component, but explicitly specifying one is strongly preferr
ed. Using a default.
```

**Comment by jzleibo** [comment]
This is probably happening because you have created some custom game objects and forgotten to list the transform component. You can get rid of the warning message without changing anything about the behavior of your environment. All you need to do is make sure all your game objects contain the following in their components dictionary `{"component": "Transform",}`.

So it will look like:

```
NEW_GAME_OBJECT = {
    "name": "new_game_object_name",
    "components": [
          ...,
          {"component": "Transform",},
          ...,
    ]
}
```

**Comment by duenez** [comment]
In particular, we don't require scene objects to be explicitly created for a level. When that happens, we just create a default one, which then triggers the warning as you see it, because it didn't have a transform specified.

**Comment by GoingMyWay** [comment]
> In particular, we don't require scene objects to be explicitly created for a level. When that happens, we just create a default one, which then triggers the warning as you see it, because it didn't have a transform specified.

Hi, actually I did not change the code. I  just ran the code in the repo and got the warnings.

**Comment by GoingMyWay** [comment]
There is no such warning in the latest version of Melting Pot. I am closing this issue.
