### ISSUE TITLE
Pylint

### ISSUE THREAD

**Issue by alan-cooney** [deepmind/meltingpot#50]
Hi - what's the standard practice for pylintrc files with Deep Mind projects?

Could we add the standard Google one to the repo, and perhaps also add a linting step the CD? Happy to commit a PR if useful.

**Comment by alan-cooney** [comment]
Thanks John!

Something like https://github.com/marketplace/actions/python-code-quality-and-lint should work

**Comment by Muff2n** [comment]
Should the .style.yapf not use equals instead of colons? i.e.
```
[style]
based_on_style = chromium
indent_width = 2 
split_before_named_assigns = True
column_limit = 80
```

**Comment by Muff2n** [comment]
Actually, I am still getting errors using this file. Would you be able to advise me please? I believe this is because chromium is not a recognised style.

Yapf says that you can choose a predefined style https://github.com/google/yapf
... based in the file style.py https://github.com/google/yapf/blob/main/yapf/yapflib/style.py
But chromium is not one of them.

**Comment by Muff2n** [comment]
Update: I was wrong about the equals signs, colons are fine. But I think you want 
`based_on_style: yapf`
That appears to be what the chromium style is now called
https://github.com/google/yapf/pull/789

**Comment by jagapiou** [comment]
Thanks for the heads-up. I think it should just be:

```
[style]
based_on_style: yapf
```

Change incoming soon.
