### ISSUE TITLE
Melting Pot Testing

### ISSUE THREAD

**Issue by LukasSchaefer** [deepmind/meltingpot#8]
Hi all!

I greatly appreciate the effort spent on not just developing the substrates as learning environments, but also spending significant time on the evaluation protocol and testing scenarios with diverse background populations.

However, I am wondering whether there are any plans for scripts of the evaluation protocol?
Some agent models are provided under `meltingpot/assets/saved_models` and I can see that test scenarios are implemented/ loadable via `meltingpot/python/scenario.py` (which I assume contains background agents?) but it is still not quite straightforward to identify how a population of trained agents could be evaluated following the protocol described in Section 4.1 of the paper (evaluate for each defined scenario with randomly sampled focal agents sampled from the provided population of trained agents). The closest provided script to such functionality seems to be the `meltingpot/python/scenario_test.py` script.

Release of any code simplifying a testing protocol as described in the paper would be quite useful!
Apologies if I missed any files/ parts in the documentation describing this procedure.

**Comment by jzleibo** [comment]
Hi Lukas, thanks for your kind words here. Are you still having trouble getting the testing procedure working? 

As for the question about whether the scenarios contain the background populations. The answer is yes. If a particular scenario tests 3 focal agents alongside 5 background agents then it will have 8 players in total in each episode. In this case the num_players attribute of the scenario will be 3 since that's the number of focal agents.

**Comment by duenez** [comment]
I'm closing this issue for now. It should be resolved, but do let me know if my understanding is incorrect :)
